version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - DATABASE_URL=duckdb:///./eschool.db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-production-secret-key-change-this
      - BACKEND_CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./uploads:/app/uploads
      - ./eschool.db:/app/eschool.db
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data:
